
name: Build InvestAi APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      - name: Flutter version
        run: flutter --version

      - name: Create Android platform via flutter create (fresh Gradle)
        run: |
          mkdir -p tmp_proj
          flutter create tmp_proj --org com.investai --project-name investai
          rm -rf android
          mv tmp_proj/android ./android
          rm -rf tmp_proj

      - name: Get packages
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release --dart-define=NOWPAY_API_KEY=${{ secrets.NOWPAY_API_KEY }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: investai-apk
          path: build/app/outputs/flutter-apk/app-release.apk
